# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGM5MmNkMjZiYThmOWFmZDVjNGQ5M2JhNjBhNTg1MDI1OWE5NzBjMzMyZTZiZmNmZmUzMzA4OTJlYmQ2N2UzZDE3MmYzNzE0MmYwMTliMTA2NjZkYjhjNTg4ZTc4MDc3YjJlNDJmYTVjMWQzZjdhNDM5ZTc3OGQ5NzdhMmE1YmQ=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: hrapp
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
