package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CandidateProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidateProfileAllPropertiesEquals(CandidateProfile expected, CandidateProfile actual) {
        assertCandidateProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertCandidateProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidateProfileAllUpdatablePropertiesEquals(CandidateProfile expected, CandidateProfile actual) {
        assertCandidateProfileUpdatableFieldsEquals(expected, actual);
        assertCandidateProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidateProfileAutoGeneratedPropertiesEquals(CandidateProfile expected, CandidateProfile actual) {
        assertThat(actual)
            .as("Verify CandidateProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidateProfileUpdatableFieldsEquals(CandidateProfile expected, CandidateProfile actual) {
        assertThat(actual)
            .as("Verify CandidateProfile relevant properties")
            .satisfies(a -> assertThat(a.getCandidateDate()).as("check candidateDate").isEqualTo(expected.getCandidateDate()))
            .satisfies(a ->
                assertThat(a.getCultivateDirection()).as("check cultivateDirection").isEqualTo(expected.getCultivateDirection())
            )
            .satisfies(a -> assertThat(a.getStability()).as("check stability").isEqualTo(expected.getStability()))
            .satisfies(a -> assertThat(a.getLearningAbility()).as("check learningAbility").isEqualTo(expected.getLearningAbility()))
            .satisfies(a ->
                assertThat(a.getCommunicationCoordination())
                    .as("check communicationCoordination")
                    .isEqualTo(expected.getCommunicationCoordination())
            )
            .satisfies(a ->
                assertThat(a.getBusinessUnderstanding()).as("check businessUnderstanding").isEqualTo(expected.getBusinessUnderstanding())
            )
            .satisfies(a -> assertThat(a.getResponsibility()).as("check responsibility").isEqualTo(expected.getResponsibility()))
            .satisfies(a -> assertThat(a.getRiskAwareness()).as("check riskAwareness").isEqualTo(expected.getRiskAwareness()))
            .satisfies(a -> assertThat(a.getJudgement()).as("check judgement").isEqualTo(expected.getJudgement()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidateProfileUpdatableRelationshipsEquals(CandidateProfile expected, CandidateProfile actual) {
        assertThat(actual)
            .as("Verify CandidateProfile relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getObserver()).as("check observer").isEqualTo(expected.getObserver()));
    }
}
