package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EvaluationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAllPropertiesEquals(Evaluation expected, Evaluation actual) {
        assertEvaluationAutoGeneratedPropertiesEquals(expected, actual);
        assertEvaluationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAllUpdatablePropertiesEquals(Evaluation expected, Evaluation actual) {
        assertEvaluationUpdatableFieldsEquals(expected, actual);
        assertEvaluationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAutoGeneratedPropertiesEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationUpdatableFieldsEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation relevant properties")
            .satisfies(a -> assertThat(a.getEvaluationName()).as("check evaluationName").isEqualTo(expected.getEvaluationName()))
            .satisfies(a -> assertThat(a.getEvaluationDate()).as("check evaluationDate").isEqualTo(expected.getEvaluationDate()))
            .satisfies(a -> assertThat(a.getPeriodLabel()).as("check periodLabel").isEqualTo(expected.getPeriodLabel()))
            .satisfies(a -> assertThat(a.getProgressStatus()).as("check progressStatus").isEqualTo(expected.getProgressStatus()))
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getStrengths()).as("check strengths").isEqualTo(expected.getStrengths()))
            .satisfies(a -> assertThat(a.getWeaknesses()).as("check weaknesses").isEqualTo(expected.getWeaknesses()))
            .satisfies(a -> assertThat(a.getSupportNeeded()).as("check supportNeeded").isEqualTo(expected.getSupportNeeded()))
            .satisfies(a -> assertThat(a.getNextTrainingFocus()).as("check nextTrainingFocus").isEqualTo(expected.getNextTrainingFocus()))
            .satisfies(a ->
                assertThat(a.getPositionAdjustmentNeeded())
                    .as("check positionAdjustmentNeeded")
                    .isEqualTo(expected.getPositionAdjustmentNeeded())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationUpdatableRelationshipsEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getTrainingGoal()).as("check trainingGoal").isEqualTo(expected.getTrainingGoal()))
            .satisfies(a -> assertThat(a.getEvaluator()).as("check evaluator").isEqualTo(expected.getEvaluator()));
    }
}
