package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImprovementPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImprovementPlanAllPropertiesEquals(ImprovementPlan expected, ImprovementPlan actual) {
        assertImprovementPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertImprovementPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImprovementPlanAllUpdatablePropertiesEquals(ImprovementPlan expected, ImprovementPlan actual) {
        assertImprovementPlanUpdatableFieldsEquals(expected, actual);
        assertImprovementPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImprovementPlanAutoGeneratedPropertiesEquals(ImprovementPlan expected, ImprovementPlan actual) {
        assertThat(actual)
            .as("Verify ImprovementPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImprovementPlanUpdatableFieldsEquals(ImprovementPlan expected, ImprovementPlan actual) {
        assertThat(actual)
            .as("Verify ImprovementPlan relevant properties")
            .satisfies(a -> assertThat(a.getPlanName()).as("check planName").isEqualTo(expected.getPlanName()))
            .satisfies(a -> assertThat(a.getPlanStatus()).as("check planStatus").isEqualTo(expected.getPlanStatus()))
            .satisfies(a -> assertThat(a.getProblemSummary()).as("check problemSummary").isEqualTo(expected.getProblemSummary()))
            .satisfies(a -> assertThat(a.getImprovementAction()).as("check improvementAction").isEqualTo(expected.getImprovementAction()))
            .satisfies(a -> assertThat(a.getOwnerName()).as("check ownerName").isEqualTo(expected.getOwnerName()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getTargetDate()).as("check targetDate").isEqualTo(expected.getTargetDate()))
            .satisfies(a -> assertThat(a.getCompletionDate()).as("check completionDate").isEqualTo(expected.getCompletionDate()))
            .satisfies(a -> assertThat(a.getReviewResult()).as("check reviewResult").isEqualTo(expected.getReviewResult()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImprovementPlanUpdatableRelationshipsEquals(ImprovementPlan expected, ImprovementPlan actual) {
        assertThat(actual)
            .as("Verify ImprovementPlan relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getSkill()).as("check skill").isEqualTo(expected.getSkill()));
    }
}
