package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KeyResponsibilityCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyResponsibilityCategoryAllPropertiesEquals(
        KeyResponsibilityCategory expected,
        KeyResponsibilityCategory actual
    ) {
        assertKeyResponsibilityCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertKeyResponsibilityCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyResponsibilityCategoryAllUpdatablePropertiesEquals(
        KeyResponsibilityCategory expected,
        KeyResponsibilityCategory actual
    ) {
        assertKeyResponsibilityCategoryUpdatableFieldsEquals(expected, actual);
        assertKeyResponsibilityCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyResponsibilityCategoryAutoGeneratedPropertiesEquals(
        KeyResponsibilityCategory expected,
        KeyResponsibilityCategory actual
    ) {
        assertThat(actual)
            .as("Verify KeyResponsibilityCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyResponsibilityCategoryUpdatableFieldsEquals(
        KeyResponsibilityCategory expected,
        KeyResponsibilityCategory actual
    ) {
        assertThat(actual)
            .as("Verify KeyResponsibilityCategory relevant properties")
            .satisfies(a -> assertThat(a.getCategoryName()).as("check categoryName").isEqualTo(expected.getCategoryName()))
            .satisfies(a -> assertThat(a.getExamples()).as("check examples").isEqualTo(expected.getExamples()))
            .satisfies(a -> assertThat(a.getRiskFocus()).as("check riskFocus").isEqualTo(expected.getRiskFocus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyResponsibilityCategoryUpdatableRelationshipsEquals(
        KeyResponsibilityCategory expected,
        KeyResponsibilityCategory actual
    ) {
        // empty method
    }
}
