package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonRiskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonRiskAllPropertiesEquals(PersonRisk expected, PersonRisk actual) {
        assertPersonRiskAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonRiskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonRiskAllUpdatablePropertiesEquals(PersonRisk expected, PersonRisk actual) {
        assertPersonRiskUpdatableFieldsEquals(expected, actual);
        assertPersonRiskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonRiskAutoGeneratedPropertiesEquals(PersonRisk expected, PersonRisk actual) {
        assertThat(actual)
            .as("Verify PersonRisk auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonRiskUpdatableFieldsEquals(PersonRisk expected, PersonRisk actual) {
        assertThat(actual)
            .as("Verify PersonRisk relevant properties")
            .satisfies(a -> assertThat(a.getRiskType()).as("check riskType").isEqualTo(expected.getRiskType()))
            .satisfies(a -> assertThat(a.getRiskLevel()).as("check riskLevel").isEqualTo(expected.getRiskLevel()))
            .satisfies(a -> assertThat(a.getRiskDescription()).as("check riskDescription").isEqualTo(expected.getRiskDescription()))
            .satisfies(a -> assertThat(a.getImprovementAction()).as("check improvementAction").isEqualTo(expected.getImprovementAction()))
            .satisfies(a -> assertThat(a.getIdentifiedDate()).as("check identifiedDate").isEqualTo(expected.getIdentifiedDate()))
            .satisfies(a -> assertThat(a.getTargetDate()).as("check targetDate").isEqualTo(expected.getTargetDate()))
            .satisfies(a -> assertThat(a.getClosedDate()).as("check closedDate").isEqualTo(expected.getClosedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonRiskUpdatableRelationshipsEquals(PersonRisk expected, PersonRisk actual) {
        assertThat(actual)
            .as("Verify PersonRisk relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }
}
