package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonSkillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonSkillAllPropertiesEquals(PersonSkill expected, PersonSkill actual) {
        assertPersonSkillAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonSkillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonSkillAllUpdatablePropertiesEquals(PersonSkill expected, PersonSkill actual) {
        assertPersonSkillUpdatableFieldsEquals(expected, actual);
        assertPersonSkillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonSkillAutoGeneratedPropertiesEquals(PersonSkill expected, PersonSkill actual) {
        assertThat(actual)
            .as("Verify PersonSkill auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonSkillUpdatableFieldsEquals(PersonSkill expected, PersonSkill actual) {
        assertThat(actual)
            .as("Verify PersonSkill relevant properties")
            .satisfies(a -> assertThat(a.getAssessmentDate()).as("check assessmentDate").isEqualTo(expected.getAssessmentDate()))
            .satisfies(a -> assertThat(a.getNextReviewDate()).as("check nextReviewDate").isEqualTo(expected.getNextReviewDate()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getGrowthDirection()).as("check growthDirection").isEqualTo(expected.getGrowthDirection()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonSkillUpdatableRelationshipsEquals(PersonSkill expected, PersonSkill actual) {
        assertThat(actual)
            .as("Verify PersonSkill relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getSkill()).as("check skill").isEqualTo(expected.getSkill()))
            .satisfies(a -> assertThat(a.getCurrentLevel()).as("check currentLevel").isEqualTo(expected.getCurrentLevel()))
            .satisfies(a -> assertThat(a.getPreviousLevel()).as("check previousLevel").isEqualTo(expected.getPreviousLevel()));
    }
}
