package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionSkillRequirementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionSkillRequirementAllPropertiesEquals(
        PositionSkillRequirement expected,
        PositionSkillRequirement actual
    ) {
        assertPositionSkillRequirementAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionSkillRequirementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionSkillRequirementAllUpdatablePropertiesEquals(
        PositionSkillRequirement expected,
        PositionSkillRequirement actual
    ) {
        assertPositionSkillRequirementUpdatableFieldsEquals(expected, actual);
        assertPositionSkillRequirementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionSkillRequirementAutoGeneratedPropertiesEquals(
        PositionSkillRequirement expected,
        PositionSkillRequirement actual
    ) {
        assertThat(actual)
            .as("Verify PositionSkillRequirement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionSkillRequirementUpdatableFieldsEquals(
        PositionSkillRequirement expected,
        PositionSkillRequirement actual
    ) {
        assertThat(actual)
            .as("Verify PositionSkillRequirement relevant properties")
            .satisfies(a -> assertThat(a.getImportance()).as("check importance").isEqualTo(expected.getImportance()))
            .satisfies(a -> assertThat(a.getRemark()).as("check remark").isEqualTo(expected.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionSkillRequirementUpdatableRelationshipsEquals(
        PositionSkillRequirement expected,
        PositionSkillRequirement actual
    ) {
        assertThat(actual)
            .as("Verify PositionSkillRequirement relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getSkill()).as("check skill").isEqualTo(expected.getSkill()))
            .satisfies(a -> assertThat(a.getRequiredLevel()).as("check requiredLevel").isEqualTo(expected.getRequiredLevel()))
            .satisfies(a -> assertThat(a.getPreferredLevel()).as("check preferredLevel").isEqualTo(expected.getPreferredLevel()));
    }
}
