package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAssignmentAllPropertiesEquals(PositionAssignment expected, PositionAssignment actual) {
        assertPositionAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAssignmentAllUpdatablePropertiesEquals(PositionAssignment expected, PositionAssignment actual) {
        assertPositionAssignmentUpdatableFieldsEquals(expected, actual);
        assertPositionAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAssignmentAutoGeneratedPropertiesEquals(PositionAssignment expected, PositionAssignment actual) {
        assertThat(actual)
            .as("Verify PositionAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAssignmentUpdatableFieldsEquals(PositionAssignment expected, PositionAssignment actual) {
        assertThat(actual)
            .as("Verify PositionAssignment relevant properties")
            .satisfies(a -> assertThat(a.getPrimaryOwner()).as("check primaryOwner").isEqualTo(expected.getPrimaryOwner()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a ->
                assertThat(a.getResponsibilityScope()).as("check responsibilityScope").isEqualTo(expected.getResponsibilityScope())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAssignmentUpdatableRelationshipsEquals(PositionAssignment expected, PositionAssignment actual) {
        assertThat(actual)
            .as("Verify PositionAssignment relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }
}
