package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllPropertiesEquals(Position expected, Position actual) {
        assertPositionAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllUpdatablePropertiesEquals(Position expected, Position actual) {
        assertPositionUpdatableFieldsEquals(expected, actual);
        assertPositionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAutoGeneratedPropertiesEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableFieldsEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position relevant properties")
            .satisfies(a -> assertThat(a.getPositionCode()).as("check positionCode").isEqualTo(expected.getPositionCode()))
            .satisfies(a -> assertThat(a.getPositionName()).as("check positionName").isEqualTo(expected.getPositionName()))
            .satisfies(a -> assertThat(a.getPositionType()).as("check positionType").isEqualTo(expected.getPositionType()))
            .satisfies(a ->
                assertThat(a.getBusinessImportance()).as("check businessImportance").isEqualTo(expected.getBusinessImportance())
            )
            .satisfies(a -> assertThat(a.getKeyPosition()).as("check keyPosition").isEqualTo(expected.getKeyPosition()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPlannedHeadcount()).as("check plannedHeadcount").isEqualTo(expected.getPlannedHeadcount()))
            .satisfies(a -> assertThat(a.getMinimumOwnerCount()).as("check minimumOwnerCount").isEqualTo(expected.getMinimumOwnerCount()))
            .satisfies(a -> assertThat(a.getReviewCycle()).as("check reviewCycle").isEqualTo(expected.getReviewCycle()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableRelationshipsEquals(Position expected, Position actual) {
        // empty method
    }
}
