package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionMatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionMatchAllPropertiesEquals(PositionMatch expected, PositionMatch actual) {
        assertPositionMatchAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionMatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionMatchAllUpdatablePropertiesEquals(PositionMatch expected, PositionMatch actual) {
        assertPositionMatchUpdatableFieldsEquals(expected, actual);
        assertPositionMatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionMatchAutoGeneratedPropertiesEquals(PositionMatch expected, PositionMatch actual) {
        assertThat(actual)
            .as("Verify PositionMatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionMatchUpdatableFieldsEquals(PositionMatch expected, PositionMatch actual) {
        assertThat(actual)
            .as("Verify PositionMatch relevant properties")
            .satisfies(a -> assertThat(a.getMatchScore()).as("check matchScore").isEqualTo(expected.getMatchScore()))
            .satisfies(a -> assertThat(a.getMatchedSkills()).as("check matchedSkills").isEqualTo(expected.getMatchedSkills()))
            .satisfies(a -> assertThat(a.getGapSkills()).as("check gapSkills").isEqualTo(expected.getGapSkills()))
            .satisfies(a -> assertThat(a.getReadiness()).as("check readiness").isEqualTo(expected.getReadiness()))
            .satisfies(a -> assertThat(a.getRecommendation()).as("check recommendation").isEqualTo(expected.getRecommendation()))
            .satisfies(a -> assertThat(a.getAnalysisDate()).as("check analysisDate").isEqualTo(expected.getAnalysisDate()))
            .satisfies(a -> assertThat(a.getRemark()).as("check remark").isEqualTo(expected.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionMatchUpdatableRelationshipsEquals(PositionMatch expected, PositionMatch actual) {
        assertThat(actual)
            .as("Verify PositionMatch relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }
}
