package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionRiskEvaluationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskEvaluationAllPropertiesEquals(PositionRiskEvaluation expected, PositionRiskEvaluation actual) {
        assertPositionRiskEvaluationAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionRiskEvaluationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskEvaluationAllUpdatablePropertiesEquals(
        PositionRiskEvaluation expected,
        PositionRiskEvaluation actual
    ) {
        assertPositionRiskEvaluationUpdatableFieldsEquals(expected, actual);
        assertPositionRiskEvaluationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskEvaluationAutoGeneratedPropertiesEquals(
        PositionRiskEvaluation expected,
        PositionRiskEvaluation actual
    ) {
        assertThat(actual)
            .as("Verify PositionRiskEvaluation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskEvaluationUpdatableFieldsEquals(PositionRiskEvaluation expected, PositionRiskEvaluation actual) {
        assertThat(actual)
            .as("Verify PositionRiskEvaluation relevant properties")
            .satisfies(a -> assertThat(a.getEvaluationDate()).as("check evaluationDate").isEqualTo(expected.getEvaluationDate()))
            .satisfies(a -> assertThat(a.getOwnerCount()).as("check ownerCount").isEqualTo(expected.getOwnerCount()))
            .satisfies(a ->
                assertThat(a.getSubstitutableOwnerCount())
                    .as("check substitutableOwnerCount")
                    .isEqualTo(expected.getSubstitutableOwnerCount())
            )
            .satisfies(a -> assertThat(a.getHasSubstitute()).as("check hasSubstitute").isEqualTo(expected.getHasSubstitute()))
            .satisfies(a -> assertThat(a.getDocumentStatus()).as("check documentStatus").isEqualTo(expected.getDocumentStatus()))
            .satisfies(a ->
                assertThat(a.getCustomerOrSystemDependency())
                    .as("check customerOrSystemDependency")
                    .isEqualTo(expected.getCustomerOrSystemDependency())
            )
            .satisfies(a ->
                assertThat(a.getSuccessionReadiness()).as("check successionReadiness").isEqualTo(expected.getSuccessionReadiness())
            )
            .satisfies(a -> assertThat(a.getRiskLevel()).as("check riskLevel").isEqualTo(expected.getRiskLevel()))
            .satisfies(a -> assertThat(a.getRiskReason()).as("check riskReason").isEqualTo(expected.getRiskReason()))
            .satisfies(a -> assertThat(a.getRecommendedAction()).as("check recommendedAction").isEqualTo(expected.getRecommendedAction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskEvaluationUpdatableRelationshipsEquals(
        PositionRiskEvaluation expected,
        PositionRiskEvaluation actual
    ) {
        assertThat(actual)
            .as("Verify PositionRiskEvaluation relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }
}
