package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PositionRiskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskAllPropertiesEquals(PositionRisk expected, PositionRisk actual) {
        assertPositionRiskAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionRiskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskAllUpdatablePropertiesEquals(PositionRisk expected, PositionRisk actual) {
        assertPositionRiskUpdatableFieldsEquals(expected, actual);
        assertPositionRiskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskAutoGeneratedPropertiesEquals(PositionRisk expected, PositionRisk actual) {
        assertThat(actual)
            .as("Verify PositionRisk auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskUpdatableFieldsEquals(PositionRisk expected, PositionRisk actual) {
        assertThat(actual)
            .as("Verify PositionRisk relevant properties")
            .satisfies(a -> assertThat(a.getRiskType()).as("check riskType").isEqualTo(expected.getRiskType()))
            .satisfies(a -> assertThat(a.getRiskLevel()).as("check riskLevel").isEqualTo(expected.getRiskLevel()))
            .satisfies(a -> assertThat(a.getDocumentStatus()).as("check documentStatus").isEqualTo(expected.getDocumentStatus()))
            .satisfies(a -> assertThat(a.getBackupStatus()).as("check backupStatus").isEqualTo(expected.getBackupStatus()))
            .satisfies(a ->
                assertThat(a.getCustomerOrSystemDependency())
                    .as("check customerOrSystemDependency")
                    .isEqualTo(expected.getCustomerOrSystemDependency())
            )
            .satisfies(a -> assertThat(a.getRiskDescription()).as("check riskDescription").isEqualTo(expected.getRiskDescription()))
            .satisfies(a -> assertThat(a.getImprovementAction()).as("check improvementAction").isEqualTo(expected.getImprovementAction()))
            .satisfies(a -> assertThat(a.getIdentifiedDate()).as("check identifiedDate").isEqualTo(expected.getIdentifiedDate()))
            .satisfies(a -> assertThat(a.getTargetDate()).as("check targetDate").isEqualTo(expected.getTargetDate()))
            .satisfies(a -> assertThat(a.getClosedDate()).as("check closedDate").isEqualTo(expected.getClosedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionRiskUpdatableRelationshipsEquals(PositionRisk expected, PositionRisk actual) {
        assertThat(actual)
            .as("Verify PositionRisk relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
