package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SkillAssessmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAssessmentAllPropertiesEquals(SkillAssessment expected, SkillAssessment actual) {
        assertSkillAssessmentAutoGeneratedPropertiesEquals(expected, actual);
        assertSkillAssessmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAssessmentAllUpdatablePropertiesEquals(SkillAssessment expected, SkillAssessment actual) {
        assertSkillAssessmentUpdatableFieldsEquals(expected, actual);
        assertSkillAssessmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAssessmentAutoGeneratedPropertiesEquals(SkillAssessment expected, SkillAssessment actual) {
        assertThat(actual)
            .as("Verify SkillAssessment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAssessmentUpdatableFieldsEquals(SkillAssessment expected, SkillAssessment actual) {
        assertThat(actual)
            .as("Verify SkillAssessment relevant properties")
            .satisfies(a -> assertThat(a.getAssessmentDate()).as("check assessmentDate").isEqualTo(expected.getAssessmentDate()))
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAssessmentUpdatableRelationshipsEquals(SkillAssessment expected, SkillAssessment actual) {
        assertThat(actual)
            .as("Verify SkillAssessment relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getSkill()).as("check skill").isEqualTo(expected.getSkill()))
            .satisfies(a -> assertThat(a.getAssessor()).as("check assessor").isEqualTo(expected.getAssessor()))
            .satisfies(a -> assertThat(a.getNewLevel()).as("check newLevel").isEqualTo(expected.getNewLevel()));
    }
}
