package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SkillUpgradeRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpgradeRecordAllPropertiesEquals(SkillUpgradeRecord expected, SkillUpgradeRecord actual) {
        assertSkillUpgradeRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertSkillUpgradeRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpgradeRecordAllUpdatablePropertiesEquals(SkillUpgradeRecord expected, SkillUpgradeRecord actual) {
        assertSkillUpgradeRecordUpdatableFieldsEquals(expected, actual);
        assertSkillUpgradeRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpgradeRecordAutoGeneratedPropertiesEquals(SkillUpgradeRecord expected, SkillUpgradeRecord actual) {
        assertThat(actual)
            .as("Verify SkillUpgradeRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpgradeRecordUpdatableFieldsEquals(SkillUpgradeRecord expected, SkillUpgradeRecord actual) {
        assertThat(actual)
            .as("Verify SkillUpgradeRecord relevant properties")
            .satisfies(a -> assertThat(a.getChangeType()).as("check changeType").isEqualTo(expected.getChangeType()))
            .satisfies(a -> assertThat(a.getChangeDate()).as("check changeDate").isEqualTo(expected.getChangeDate()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getBeforeLevelLabel()).as("check beforeLevelLabel").isEqualTo(expected.getBeforeLevelLabel()))
            .satisfies(a -> assertThat(a.getAfterLevelLabel()).as("check afterLevelLabel").isEqualTo(expected.getAfterLevelLabel()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpgradeRecordUpdatableRelationshipsEquals(SkillUpgradeRecord expected, SkillUpgradeRecord actual) {
        assertThat(actual)
            .as("Verify SkillUpgradeRecord relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getSkill()).as("check skill").isEqualTo(expected.getSkill()))
            .satisfies(a -> assertThat(a.getOldLevel()).as("check oldLevel").isEqualTo(expected.getOldLevel()))
            .satisfies(a -> assertThat(a.getNewLevel()).as("check newLevel").isEqualTo(expected.getNewLevel()))
            .satisfies(a -> assertThat(a.getAssessor()).as("check assessor").isEqualTo(expected.getAssessor()));
    }
}
