package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SkillLevelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillLevelAllPropertiesEquals(SkillLevel expected, SkillLevel actual) {
        assertSkillLevelAutoGeneratedPropertiesEquals(expected, actual);
        assertSkillLevelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillLevelAllUpdatablePropertiesEquals(SkillLevel expected, SkillLevel actual) {
        assertSkillLevelUpdatableFieldsEquals(expected, actual);
        assertSkillLevelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillLevelAutoGeneratedPropertiesEquals(SkillLevel expected, SkillLevel actual) {
        assertThat(actual)
            .as("Verify SkillLevel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillLevelUpdatableFieldsEquals(SkillLevel expected, SkillLevel actual) {
        assertThat(actual)
            .as("Verify SkillLevel relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLevelName()).as("check levelName").isEqualTo(expected.getLevelName()))
            .satisfies(a -> assertThat(a.getDefinition()).as("check definition").isEqualTo(expected.getDefinition()))
            .satisfies(a ->
                assertThat(a.getObservableEvidence()).as("check observableEvidence").isEqualTo(expected.getObservableEvidence())
            )
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillLevelUpdatableRelationshipsEquals(SkillLevel expected, SkillLevel actual) {
        // empty method
    }
}
