package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SkillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAllPropertiesEquals(Skill expected, Skill actual) {
        assertSkillAutoGeneratedPropertiesEquals(expected, actual);
        assertSkillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAllUpdatablePropertiesEquals(Skill expected, Skill actual) {
        assertSkillUpdatableFieldsEquals(expected, actual);
        assertSkillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillAutoGeneratedPropertiesEquals(Skill expected, Skill actual) {
        assertThat(actual)
            .as("Verify Skill auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpdatableFieldsEquals(Skill expected, Skill actual) {
        assertThat(actual)
            .as("Verify Skill relevant properties")
            .satisfies(a -> assertThat(a.getSkillCode()).as("check skillCode").isEqualTo(expected.getSkillCode()))
            .satisfies(a -> assertThat(a.getSkillName()).as("check skillName").isEqualTo(expected.getSkillName()))
            .satisfies(a -> assertThat(a.getSkillType()).as("check skillType").isEqualTo(expected.getSkillType()))
            .satisfies(a -> assertThat(a.getMeasurableFlag()).as("check measurableFlag").isEqualTo(expected.getMeasurableFlag()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getEvidenceType()).as("check evidenceType").isEqualTo(expected.getEvidenceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillUpdatableRelationshipsEquals(Skill expected, Skill actual) {
        // empty method
    }
}
