package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static top.btmdc.hr.domain.AssertUtils.bigDecimalCompareTo;

public class StaffSubstitutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffSubstitutionAllPropertiesEquals(StaffSubstitution expected, StaffSubstitution actual) {
        assertStaffSubstitutionAutoGeneratedPropertiesEquals(expected, actual);
        assertStaffSubstitutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffSubstitutionAllUpdatablePropertiesEquals(StaffSubstitution expected, StaffSubstitution actual) {
        assertStaffSubstitutionUpdatableFieldsEquals(expected, actual);
        assertStaffSubstitutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffSubstitutionAutoGeneratedPropertiesEquals(StaffSubstitution expected, StaffSubstitution actual) {
        assertThat(actual)
            .as("Verify StaffSubstitution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffSubstitutionUpdatableFieldsEquals(StaffSubstitution expected, StaffSubstitution actual) {
        assertThat(actual)
            .as("Verify StaffSubstitution relevant properties")
            .satisfies(a ->
                assertThat(a.getCoverageRate())
                    .as("check coverageRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCoverageRate())
            )
            .satisfies(a ->
                assertThat(a.getThresholdRate())
                    .as("check thresholdRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getThresholdRate())
            )
            .satisfies(a -> assertThat(a.getTotalSkillCount()).as("check totalSkillCount").isEqualTo(expected.getTotalSkillCount()))
            .satisfies(a -> assertThat(a.getCoveredSkillCount()).as("check coveredSkillCount").isEqualTo(expected.getCoveredSkillCount()))
            .satisfies(a -> assertThat(a.getMissingSkills()).as("check missingSkills").isEqualTo(expected.getMissingSkills()))
            .satisfies(a -> assertThat(a.getSubstitutable()).as("check substitutable").isEqualTo(expected.getSubstitutable()))
            .satisfies(a -> assertThat(a.getEvaluationDate()).as("check evaluationDate").isEqualTo(expected.getEvaluationDate()))
            .satisfies(a -> assertThat(a.getReviewDate()).as("check reviewDate").isEqualTo(expected.getReviewDate()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffSubstitutionUpdatableRelationshipsEquals(StaffSubstitution expected, StaffSubstitution actual) {
        assertThat(actual)
            .as("Verify StaffSubstitution relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getCandidatePerson()).as("check candidatePerson").isEqualTo(expected.getCandidatePerson()));
    }
}
