package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SuccessionCandidateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuccessionCandidateAllPropertiesEquals(SuccessionCandidate expected, SuccessionCandidate actual) {
        assertSuccessionCandidateAutoGeneratedPropertiesEquals(expected, actual);
        assertSuccessionCandidateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuccessionCandidateAllUpdatablePropertiesEquals(SuccessionCandidate expected, SuccessionCandidate actual) {
        assertSuccessionCandidateUpdatableFieldsEquals(expected, actual);
        assertSuccessionCandidateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuccessionCandidateAutoGeneratedPropertiesEquals(SuccessionCandidate expected, SuccessionCandidate actual) {
        assertThat(actual)
            .as("Verify SuccessionCandidate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuccessionCandidateUpdatableFieldsEquals(SuccessionCandidate expected, SuccessionCandidate actual) {
        assertThat(actual)
            .as("Verify SuccessionCandidate relevant properties")
            .satisfies(a ->
                assertThat(a.getSuccessionReadiness()).as("check successionReadiness").isEqualTo(expected.getSuccessionReadiness())
            )
            .satisfies(a -> assertThat(a.getRequiredTraining()).as("check requiredTraining").isEqualTo(expected.getRequiredTraining()))
            .satisfies(a ->
                assertThat(a.getEstimatedTimeToReady()).as("check estimatedTimeToReady").isEqualTo(expected.getEstimatedTimeToReady())
            )
            .satisfies(a -> assertThat(a.getRiskAfterTraining()).as("check riskAfterTraining").isEqualTo(expected.getRiskAfterTraining()))
            .satisfies(a -> assertThat(a.getReviewDate()).as("check reviewDate").isEqualTo(expected.getReviewDate()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuccessionCandidateUpdatableRelationshipsEquals(SuccessionCandidate expected, SuccessionCandidate actual) {
        assertThat(actual)
            .as("Verify SuccessionCandidate relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getCurrentOwner()).as("check currentOwner").isEqualTo(expected.getCurrentOwner()))
            .satisfies(a -> assertThat(a.getCandidate()).as("check candidate").isEqualTo(expected.getCandidate()));
    }
}
