package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrainingRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRecordAllPropertiesEquals(TrainingRecord expected, TrainingRecord actual) {
        assertTrainingRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertTrainingRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRecordAllUpdatablePropertiesEquals(TrainingRecord expected, TrainingRecord actual) {
        assertTrainingRecordUpdatableFieldsEquals(expected, actual);
        assertTrainingRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRecordAutoGeneratedPropertiesEquals(TrainingRecord expected, TrainingRecord actual) {
        assertThat(actual)
            .as("Verify TrainingRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRecordUpdatableFieldsEquals(TrainingRecord expected, TrainingRecord actual) {
        assertThat(actual)
            .as("Verify TrainingRecord relevant properties")
            .satisfies(a -> assertThat(a.getTrainingDate()).as("check trainingDate").isEqualTo(expected.getTrainingDate()))
            .satisfies(a -> assertThat(a.getTrainingType()).as("check trainingType").isEqualTo(expected.getTrainingType()))
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()))
            .satisfies(a -> assertThat(a.getTaskDescription()).as("check taskDescription").isEqualTo(expected.getTaskDescription()))
            .satisfies(a -> assertThat(a.getResultDescription()).as("check resultDescription").isEqualTo(expected.getResultDescription()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()))
            .satisfies(a -> assertThat(a.getNextAction()).as("check nextAction").isEqualTo(expected.getNextAction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRecordUpdatableRelationshipsEquals(TrainingRecord expected, TrainingRecord actual) {
        assertThat(actual)
            .as("Verify TrainingRecord relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getTrainingGoal()).as("check trainingGoal").isEqualTo(expected.getTrainingGoal()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getMentor()).as("check mentor").isEqualTo(expected.getMentor()));
    }
}
