package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrainingGoalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingGoalAllPropertiesEquals(TrainingGoal expected, TrainingGoal actual) {
        assertTrainingGoalAutoGeneratedPropertiesEquals(expected, actual);
        assertTrainingGoalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingGoalAllUpdatablePropertiesEquals(TrainingGoal expected, TrainingGoal actual) {
        assertTrainingGoalUpdatableFieldsEquals(expected, actual);
        assertTrainingGoalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingGoalAutoGeneratedPropertiesEquals(TrainingGoal expected, TrainingGoal actual) {
        assertThat(actual)
            .as("Verify TrainingGoal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingGoalUpdatableFieldsEquals(TrainingGoal expected, TrainingGoal actual) {
        assertThat(actual)
            .as("Verify TrainingGoal relevant properties")
            .satisfies(a -> assertThat(a.getGoalName()).as("check goalName").isEqualTo(expected.getGoalName()))
            .satisfies(a -> assertThat(a.getGoalDescription()).as("check goalDescription").isEqualTo(expected.getGoalDescription()))
            .satisfies(a ->
                assertThat(a.getTargetLevelDescription()).as("check targetLevelDescription").isEqualTo(expected.getTargetLevelDescription())
            )
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getTargetDate()).as("check targetDate").isEqualTo(expected.getTargetDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingGoalUpdatableRelationshipsEquals(TrainingGoal expected, TrainingGoal actual) {
        assertThat(actual)
            .as("Verify TrainingGoal relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getSkill()).as("check skill").isEqualTo(expected.getSkill()))
            .satisfies(a -> assertThat(a.getTargetLevel()).as("check targetLevel").isEqualTo(expected.getTargetLevel()));
    }
}
