package top.btmdc.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrustObservationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrustObservationAllPropertiesEquals(TrustObservation expected, TrustObservation actual) {
        assertTrustObservationAutoGeneratedPropertiesEquals(expected, actual);
        assertTrustObservationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrustObservationAllUpdatablePropertiesEquals(TrustObservation expected, TrustObservation actual) {
        assertTrustObservationUpdatableFieldsEquals(expected, actual);
        assertTrustObservationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrustObservationAutoGeneratedPropertiesEquals(TrustObservation expected, TrustObservation actual) {
        assertThat(actual)
            .as("Verify TrustObservation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrustObservationUpdatableFieldsEquals(TrustObservation expected, TrustObservation actual) {
        assertThat(actual)
            .as("Verify TrustObservation relevant properties")
            .satisfies(a -> assertThat(a.getObservationDate()).as("check observationDate").isEqualTo(expected.getObservationDate()))
            .satisfies(a -> assertThat(a.getTrustStage()).as("check trustStage").isEqualTo(expected.getTrustStage()))
            .satisfies(a -> assertThat(a.getObservedBehavior()).as("check observedBehavior").isEqualTo(expected.getObservedBehavior()))
            .satisfies(a -> assertThat(a.getPositiveSignal()).as("check positiveSignal").isEqualTo(expected.getPositiveSignal()))
            .satisfies(a -> assertThat(a.getRiskSignal()).as("check riskSignal").isEqualTo(expected.getRiskSignal()))
            .satisfies(a ->
                assertThat(a.getNextObservationPoint()).as("check nextObservationPoint").isEqualTo(expected.getNextObservationPoint())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrustObservationUpdatableRelationshipsEquals(TrustObservation expected, TrustObservation actual) {
        assertThat(actual)
            .as("Verify TrustObservation relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getObserver()).as("check observer").isEqualTo(expected.getObserver()));
    }
}
