export enum AssessmentSource {
  SELF_ASSESSMENT = 'SELF_ASSESSMENT',
  MANAGER_ASSESSMENT = 'MANAGER_ASSESSMENT',
  CERTIFICATION = 'CERTIFICATION',
  PEER_REVIEW = 'PEER_REVIEW',
  OTHER = 'OTHER',
}
