export enum EmploymentStatus {
  NEWCOMER = 'NEWCOMER',

  INDEPENDENT_STAFF = 'INDEPENDENT_STAFF',

  CORE_STAFF = 'CORE_STAFF',

  MANAGEMENT_CANDIDATE = 'MANAGEMENT_CANDIDATE',

  OBSERVE = 'OBSERVE',
}
