export enum EvidenceType {
  CERTIFICATE = 'CERTIFICATE',

  PROJECT_EXPERIENCE = 'PROJECT_EXPERIENCE',

  OBSERVATION = 'OBSERVATION',

  ASSESSMENT_RESULT = 'ASSESSMENT_RESULT',

  OTHER = 'OTHER',
}
