export enum PositionType {
  TECHNICAL = 'TECHNICAL',

  BUSINESS_SUPPORT = 'BUSINESS_SUPPORT',

  CUSTOMER_INTERFACE = 'CUSTOMER_INTERFACE',

  MANAGEMENT_SUPPORT = 'MANAGEMENT_SUPPORT',

  MENTOR = 'MENTOR',

  OTHER = 'OTHER',
}
