export enum RiskType {
  SINGLE_POINT = 'SINGLE_POINT',

  KNOWLEDGE_CONCENTRATION = 'KNOWLEDGE_CONCENTRATION',

  CUSTOMER_RELATION_CONCENTRATION = 'CUSTOMER_RELATION_CONCENTRATION',

  PERMISSION_CONCENTRATION = 'PERMISSION_CONCENTRATION',

  SUCCESSOR_SHORTAGE = 'SUCCESSOR_SHORTAGE',

  HEALTH_CONTINUITY = 'HEALTH_CONTINUITY',

  UNCLEAR_RESPONSIBILITY = 'UNCLEAR_RESPONSIBILITY',

  TURNOVER = 'TURNOVER',

  OTHER = 'OTHER',
}
