export enum TrainingType {
  ONBOARDING = 'ONBOARDING',

  SHADOWING = 'SHADOWING',

  CASE_REVIEW = 'CASE_REVIEW',

  PRACTICE = 'PRACTICE',

  MEETING = 'MEETING',

  DOCUMENTATION = 'DOCUMENTATION',

  OTHER = 'OTHER',
}
