export enum TrustStage {
  S0_UNOBSERVED = 'S0_UNOBSERVED',

  S1_BASIC_TRUST = 'S1_BASIC_TRUST',

  S2_TASK_TRUST = 'S2_TASK_TRUST',

  S3_RESPONSIBILITY_TRUST = 'S3_RESPONSIBILITY_TRUST',

  S4_KEY_TRUST = 'S4_KEY_TRUST',
}
